name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test-frontend:
    name: Frontend lint + test + build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:run

      - name: Build
        run: npm run build

  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential python3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
